In [1]:
import statsapi
import pandas as pd
from pandas import Series, DataFrame

In [2]:
# Given dictionary
data = statsapi.player_stat_data(statsapi.lookup_player('ohtani, shohei')[0]['id'], group="pitching", type="yearByYear", sportId=1)

# Flatten the dictionary and extract stats for each season
player_stats = []
for season_stats in data['stats']:
    season_data = season_stats['stats']
    season_data['season'] = season_stats['season']
    player_stats.append(season_data)

# Create DataFrame from the list of dictionaries
ohtani_df = pd.DataFrame(player_stats)

# Display DataFrame
ohtani_df

,gamesPlayed,gamesStarted,groundOuts,airOuts,runs,doubles,triples,homeRuns,strikeOuts,baseOnBalls,...,walksPer9Inn,hitsPer9Inn,runsScoredPer9,homeRunsPer9,inheritedRunners,inheritedRunnersScored,catchersInterference,sacBunts,sacFlies,season
0,10,10,37,50,19,6,0,6,63,22,...,3.83,6.62,3.31,1.05,0,0,0,0,1,2018
1,2,2,0,2,7,0,0,0,3,8,...,43.20,16.20,37.80,0.00,0,0,0,0,0,2020
2,23,23,113,112,48,23,0,15,156,44,...,3.04,6.77,3.31,1.04,0,0,0,2,4,2021
3,28,28,129,141,45,23,2,14,219,44,...,2.39,6.72,2.44,0.76,0,0,1,0,3,2022
4,23,23,114,98,50,15,0,18,167,55,...,3.75,5.80,3.41,1.23,0,0,1,0,1,2023

In [3]:
# Column to move to the front
column_to_move = 'season'

# Extract the column
column = ohtani_df[column_to_move]

# Drop the column from its original position
ohtani_df.drop(columns=[column_to_move], inplace=True)

# Insert the column at the front
ohtani_df.insert(0, column_to_move, column)

ohtani_df.insert(0, 'name', 'Shohei Ohtani')

# Display the DataFrame
ohtani_df

,name,season,gamesPlayed,gamesStarted,groundOuts,airOuts,runs,doubles,triples,homeRuns,...,strikeoutsPer9Inn,walksPer9Inn,hitsPer9Inn,runsScoredPer9,homeRunsPer9,inheritedRunners,inheritedRunnersScored,catchersInterference,sacBunts,sacFlies
0,Shohei Ohtani,2018,10,10,37,50,19,6,0,6,...,10.97,3.83,6.62,3.31,1.05,0,0,0,0,1
1,Shohei Ohtani,2020,2,2,0,2,7,0,0,0,...,16.20,43.20,16.20,37.80,0.00,0,0,0,0,0
2,Shohei Ohtani,2021,23,23,113,112,48,23,0,15,...,10.77,3.04,6.77,3.31,1.04,0,0,0,2,4
3,Shohei Ohtani,2022,28,28,129,141,45,23,2,14,...,11.87,2.39,6.72,2.44,0.76,0,0,1,0,3
4,Shohei Ohtani,2023,23,23,114,98,50,15,0,18,...,11.39,3.75,5.80,3.41,1.23,0,0,1,0,1

In [5]:
columns_to_keep = ['name', 'season', 'gamesStarted', 'wins', 'losses', 'inningsPitched', 'era', 'earnedRuns', 'avg', 'ops', 'whip', 'strikeOuts', 'strikeoutWalkRatio', 'totalBases', 'walksPer9Inn', 'hitsPer9Inn', 'runsScoredPer9']
ohtani_pitch = ohtani_df.loc[:, columns_to_keep]
ohtani_pitch

,name,season,gamesStarted,wins,losses,inningsPitched,era,earnedRuns,avg,ops,whip,strikeOuts,strikeoutWalkRatio,totalBases,walksPer9Inn,hitsPer9Inn,runsScoredPer9
0,Shohei Ohtani,2018,10,4,2,51.2,3.31,19,.203,.621,1.16,63,2.86,62,3.83,6.62,3.31
1,Shohei Ohtani,2020,2,0,1,1.2,37.80,7,.375,1.063,6.60,3,0.38,3,43.20,16.20,37.80
2,Shohei Ohtani,2021,23,9,2,130.1,3.18,46,.207,.637,1.09,156,3.55,166,3.04,6.77,3.31
3,Shohei Ohtani,2022,28,15,9,166.0,2.33,43,.203,.574,1.01,219,4.98,193,2.39,6.72,2.44
4,Shohei Ohtani,2023,23,10,5,132.0,3.14,46,.184,.618,1.06,167,3.04,154,3.75,5.80,3.41

In [13]:
ohtani_pitch_comp = ohtani_pitch[ohtani_pitch['season'] == '2022']
ohtani_pitch_comp

,name,season,gamesStarted,wins,losses,inningsPitched,era,earnedRuns,avg,ops,whip,strikeOuts,strikeoutWalkRatio,totalBases,walksPer9Inn,hitsPer9Inn,runsScoredPer9
3,Shohei Ohtani,2022,28,15,9,166.0,2.33,43,.203,.574,1.01,219,4.98,193,2.39,6.72,2.44

In [8]:
# Given dictionary
data = statsapi.player_stat_data(statsapi.lookup_player('cole, gerrit')[0]['id'], group="pitching", type="yearByYear", sportId=1)

# Flatten the dictionary and extract stats for each season
player_stats = []
for season_stats in data['stats']:
    season_data = season_stats['stats']
    season_data['season'] = season_stats['season']
    player_stats.append(season_data)

# Create DataFrame from the list of dictionaries
cole_df = pd.DataFrame(player_stats)

# Display DataFrame
cole_df

,gamesPlayed,gamesStarted,groundOuts,airOuts,runs,doubles,triples,homeRuns,strikeOuts,baseOnBalls,...,walksPer9Inn,hitsPer9Inn,runsScoredPer9,homeRunsPer9,inheritedRunners,inheritedRunnersScored,catchersInterference,sacBunts,sacFlies,season
0,19,19,137,92,43,15,0,7,100,28,...,2.15,8.36,3.30,0.54,0,0,0,5,2,2013
1,22,22,151,106,58,24,5,11,138,40,...,2.61,8.28,3.78,0.72,0,0,0,10,0,2014
2,32,32,224,169,71,31,5,11,202,44,...,1.90,7.92,3.07,0.48,0,0,0,7,6,2015
3,21,21,130,105,57,32,1,7,98,36,...,2.79,10.16,4.42,0.54,0,0,0,4,6,2016
4,33,33,217,178,98,36,6,31,196,55,...,2.44,8.82,4.34,1.37,0,0,0,5,1,2017
5,32,32,124,185,68,36,2,19,276,64,...,2.88,6.42,3.05,0.85,0,0,0,2,3,2018
6,33,33,134,164,66,30,1,29,326,48,...,2.03,6.02,2.80,1.23,0,0,0,1,3,2019
7,12,12,53,69,27,14,0,14,94,17,...,2.10,6.53,3.33,1.73,0,0,0,0,0,2020
8,30,30,138,151,69,27,1,24,243,41,...,2.03,7.49,3.42,1.19,0,0,0,0,6,2021
9,33,33,165,164,81,31,2,33,257,50,...,2.24,6.91,3.63,1.48,0,0,1,0,2,2022
10,33,33,173,213,64,26,1,20,222,48,...,2.07,6.76,2.76,0.86,0,0,1,2,2,2023

In [9]:
# Column to move to the front
column_to_move = 'season'

# Extract the column
column = cole_df[column_to_move]

# Drop the column from its original position
cole_df.drop(columns=[column_to_move], inplace=True)

# Insert the column at the front
cole_df.insert(0, column_to_move, column)

cole_df.insert(0, 'name', 'Gerrit Cole')

# Display the DataFrame
cole_df

,name,season,gamesPlayed,gamesStarted,groundOuts,airOuts,runs,doubles,triples,homeRuns,...,strikeoutsPer9Inn,walksPer9Inn,hitsPer9Inn,runsScoredPer9,homeRunsPer9,inheritedRunners,inheritedRunnersScored,catchersInterference,sacBunts,sacFlies
0,Gerrit Cole,2013,19,19,137,92,43,15,0,7,...,7.67,2.15,8.36,3.30,0.54,0,0,0,5,2
1,Gerrit Cole,2014,22,22,151,106,58,24,5,11,...,9.00,2.61,8.28,3.78,0.72,0,0,0,10,0
2,Gerrit Cole,2015,32,32,224,169,71,31,5,11,...,8.74,1.90,7.92,3.07,0.48,0,0,0,7,6
3,Gerrit Cole,2016,21,21,130,105,57,32,1,7,...,7.60,2.79,10.16,4.42,0.54,0,0,0,4,6
4,Gerrit Cole,2017,33,33,217,178,98,36,6,31,...,8.69,2.44,8.82,4.34,1.37,0,0,0,5,1
5,Gerrit Cole,2018,32,32,124,185,68,36,2,19,...,12.40,2.88,6.42,3.05,0.85,0,0,0,2,3
6,Gerrit Cole,2019,33,33,134,164,66,30,1,29,...,13.82,2.03,6.02,2.80,1.23,0,0,0,1,3
7,Gerrit Cole,2020,12,12,53,69,27,14,0,14,...,11.59,2.10,6.53,3.33,1.73,0,0,0,0,0
8,Gerrit Cole,2021,30,30,138,151,69,27,1,24,...,12.06,2.03,7.49,3.42,1.19,0,0,0,0,6
9,Gerrit Cole,2022,33,33,165,164,81,31,2,33,...,11.53,2.24,6.91,3.63,1.48,0,0,1,0,2
10,Gerrit Cole,2023,33,33,173,213,64,26,1,20,...,9.56,2.07,6.76,2.76,0.86,0,0,1,2,2

In [10]:
cole_pitch = cole_df.loc[:, columns_to_keep]
cole_pitch

,name,season,gamesStarted,wins,losses,inningsPitched,era,earnedRuns,avg,ops,whip,strikeOuts,strikeoutWalkRatio,totalBases,walksPer9Inn,hitsPer9Inn,runsScoredPer9
0,Gerrit Cole,2013,19,10,7,117.1,3.22,42,.253,.638,1.17,100,3.57,145,2.15,8.36,3.30
1,Gerrit Cole,2014,22,11,5,138.0,3.65,56,.248,.693,1.21,138,3.45,194,2.61,8.28,3.78
2,Gerrit Cole,2015,32,19,8,208.0,2.60,60,.239,.623,1.09,202,4.59,257,1.90,7.92,3.07
3,Gerrit Cole,2016,21,7,10,116.0,3.88,50,.289,.755,1.44,98,2.72,186,2.79,10.16,4.42
4,Gerrit Cole,2017,33,12,12,203.0,4.26,96,.254,.740,1.25,196,3.56,340,2.44,8.82,4.34
5,Gerrit Cole,2018,32,15,5,200.1,2.88,64,.198,.601,1.03,276,4.31,240,2.88,6.42,3.05
6,Gerrit Cole,2019,33,20,5,212.1,2.50,59,.186,.580,0.89,326,6.79,261,2.03,6.02,2.80
7,Gerrit Cole,2020,12,7,3,73.0,2.84,23,.197,.655,0.96,94,5.53,109,2.10,6.53,3.33
8,Gerrit Cole,2021,30,16,8,181.1,3.23,65,.223,.639,1.06,243,5.93,252,2.03,7.49,3.42
9,Gerrit Cole,2022,33,13,8,200.2,3.50,78,.209,.650,1.02,257,5.14,288,2.24,6.91,3.63
10,Gerrit Cole,2023,33,15,4,209.0,2.63,61,.206,.581,0.98,222,4.63,245,2.07,6.76,2.76

In [11]:
cole_pitch_comp = cole_pitch[cole_pitch['season'] == '2023']
cole_pitch_comp

,name,season,gamesStarted,wins,losses,inningsPitched,era,earnedRuns,avg,ops,whip,strikeOuts,strikeoutWalkRatio,totalBases,walksPer9Inn,hitsPer9Inn,runsScoredPer9
10,Gerrit Cole,2023,33,15,4,209.0,2.63,61,.206,.581,0.98,222,4.63,245,2.07,6.76,2.76

In [14]:
ohtani_pitch_comp = pd.concat([ohtani_pitch_comp, cole_pitch_comp], ignore_index=True)
ohtani_pitch_comp

,name,season,gamesStarted,wins,losses,inningsPitched,era,earnedRuns,avg,ops,whip,strikeOuts,strikeoutWalkRatio,totalBases,walksPer9Inn,hitsPer9Inn,runsScoredPer9
0,Shohei Ohtani,2022,28,15,9,166.0,2.33,43,.203,.574,1.01,219,4.98,193,2.39,6.72,2.44
1,Gerrit Cole,2023,33,15,4,209.0,2.63,61,.206,.581,0.98,222,4.63,245,2.07,6.76,2.76

In [15]:
# Given dictionary
data = statsapi.player_stat_data(statsapi.lookup_player('verlander, justin')[0]['id'], group="pitching", type="yearByYear", sportId=1)

# Flatten the dictionary and extract stats for each season
player_stats = []
for season_stats in data['stats']:
    season_data = season_stats['stats']
    season_data['season'] = season_stats['season']
    player_stats.append(season_data)

# Create DataFrame from the list of dictionaries
verlander_df = pd.DataFrame(player_stats)

# Display DataFrame
verlander_df

,gamesPlayed,gamesStarted,groundOuts,airOuts,runs,doubles,triples,homeRuns,strikeOuts,baseOnBalls,...,walksPer9Inn,hitsPer9Inn,runsScoredPer9,homeRunsPer9,inheritedRunners,inheritedRunnersScored,catchersInterference,sacBunts,sacFlies,season
0,2,2,15,11,9,5,0,1,7,5,...,3.97,11.91,7.15,0.79,0,0,0,0,0,2005
1,30,30,195,203,78,33,4,21,124,60,...,2.90,9.05,3.77,1.02,0,0,1,2,4,2006
2,32,32,186,230,88,33,2,20,183,67,...,2.99,8.08,3.93,0.89,0,0,0,3,1,2007
3,33,33,182,239,119,39,1,18,163,87,...,3.90,8.73,5.33,0.81,0,0,0,4,6,2008
4,35,35,172,252,99,50,2,20,269,63,...,2.36,8.21,3.71,0.75,0,0,1,6,4,2009
5,33,33,205,234,89,37,7,14,219,71,...,2.85,7.62,3.57,0.56,0,0,0,6,8,2010
6,34,34,215,270,73,31,3,24,250,57,...,2.04,6.24,2.62,0.86,0,0,0,2,3,2011
7,33,33,230,230,81,40,2,19,239,60,...,2.27,7.25,3.06,0.72,0,0,0,4,3,2012
8,34,34,176,241,94,38,4,19,217,75,...,3.09,8.74,3.87,0.78,0,0,0,2,6,2013
9,32,32,186,255,114,51,9,18,159,65,...,2.84,9.74,4.98,0.79,0,0,0,6,5,2014
10,20,20,99,175,56,20,2,13,113,32,...,2.16,7.63,3.78,0.88,0,0,0,1,6,2015
11,34,34,153,260,81,35,4,30,254,57,...,2.25,6.76,3.20,1.19,0,0,0,4,7,2016
12,28,28,124,206,76,27,2,23,176,67,...,3.51,8.01,3.98,1.20,0,0,0,1,4,2017
13,5,5,22,32,4,2,0,4,43,5,...,1.32,4.50,1.06,1.06,0,0,0,0,0,2017
14,33,33,146,238,80,29,2,27,219,72,...,3.15,7.43,3.50,1.18,0,0,0,1,4,2017
15,34,34,105,237,63,31,5,28,290,37,...,1.56,6.56,2.65,1.18,0,0,0,2,5,2018
16,34,34,150,211,66,28,7,36,300,42,...,1.70,5.53,2.66,1.45,0,0,1,0,2,2019
17,1,1,7,3,2,0,0,2,7,1,...,1.50,4.50,3.00,3.00,0,0,0,0,0,2020
18,28,28,131,199,43,15,1,12,185,29,...,1.49,5.97,2.21,0.62,0,0,0,1,5,2022
19,16,16,75,121,36,17,0,9,81,31,...,2.96,7.35,3.43,0.86,0,0,0,0,2,2023
20,11,11,47,93,27,13,2,9,63,14,...,1.85,8.21,3.57,1.19,0,0,0,0,2,2023
21,27,27,122,214,63,30,2,18,144,45,...,2.49,7.71,3.49,1.00,0,0,0,0,4,2023

In [16]:
# Column to move to the front
column_to_move = 'season'

# Extract the column
column = verlander_df[column_to_move]

# Drop the column from its original position
verlander_df.drop(columns=[column_to_move], inplace=True)

# Insert the column at the front
verlander_df.insert(0, column_to_move, column)

verlander_df.insert(0, 'name', 'Justin Verlander')

verlander_pitch = verlander_df.loc[:, columns_to_keep]

verlander_pitch_comp = verlander_pitch[verlander_pitch['season'] == '2022']
verlander_pitch_comp

,name,season,gamesStarted,wins,losses,inningsPitched,era,earnedRuns,avg,ops,whip,strikeOuts,strikeoutWalkRatio,totalBases,walksPer9Inn,hitsPer9Inn,runsScoredPer9
18,Justin Verlander,2022,28,18,4,175.0,1.75,34,.186,.497,0.83,185,6.38,169,1.49,5.97,2.21

In [17]:
ohtani_pitch_comp = pd.concat([ohtani_pitch_comp, verlander_pitch_comp], ignore_index=True)
ohtani_pitch_comp

,name,season,gamesStarted,wins,losses,inningsPitched,era,earnedRuns,avg,ops,whip,strikeOuts,strikeoutWalkRatio,totalBases,walksPer9Inn,hitsPer9Inn,runsScoredPer9
0,Shohei Ohtani,2022,28,15,9,166.0,2.33,43,.203,.574,1.01,219,4.98,193,2.39,6.72,2.44
1,Gerrit Cole,2023,33,15,4,209.0,2.63,61,.206,.581,0.98,222,4.63,245,2.07,6.76,2.76
2,Justin Verlander,2022,28,18,4,175.0,1.75,34,.186,.497,0.83,185,6.38,169,1.49,5.97,2.21

In [23]:
# Given dictionary
data = statsapi.player_stat_data(592662, group="pitching", type="yearByYear", sportId=1)

# Flatten the dictionary and extract stats for each season
player_stats = []
for season_stats in data['stats']:
    season_data = season_stats['stats']
    season_data['season'] = season_stats['season']
    player_stats.append(season_data)

# Create DataFrame from the list of dictionaries
ray_df = pd.DataFrame(player_stats)

# Display DataFrame
ray_df

,gamesPlayed,gamesStarted,groundOuts,airOuts,runs,doubles,triples,homeRuns,strikeOuts,baseOnBalls,...,walksPer9Inn,hitsPer9Inn,runsScoredPer9,homeRunsPer9,inheritedRunners,inheritedRunnersScored,catchersInterference,sacBunts,sacFlies,season
0,9,6,28,35,26,13,1,5,19,11,...,3.45,13.50,8.16,1.57,0,0,0,1,1,2014
1,23,23,123,125,56,30,6,9,119,49,...,3.45,8.53,3.95,0.63,0,0,0,7,6,2015
2,32,32,162,134,105,32,5,24,218,71,...,3.67,9.55,5.42,1.24,0,0,0,3,2,2016
3,28,28,114,141,57,18,2,23,218,71,...,3.94,6.44,3.17,1.28,0,0,0,4,3,2017
4,24,24,93,96,55,16,0,19,165,70,...,5.09,7.06,4.00,1.38,0,0,0,1,1,2018
5,33,33,132,140,91,33,5,30,235,84,...,4.34,7.74,4.70,1.55,0,0,1,11,4,2019
6,7,7,12,36,27,9,0,9,43,31,...,9.00,9.00,7.84,2.61,0,0,0,0,2,2020
7,5,4,14,22,13,5,0,4,25,14,...,6.10,9.58,5.66,1.74,0,0,0,0,0,2020
8,12,11,26,58,40,14,0,13,68,45,...,7.84,9.23,6.97,2.26,0,0,0,0,2,2020
9,32,32,133,186,62,31,3,33,248,52,...,2.42,6.98,2.89,1.54,0,0,0,1,2,2021
10,32,32,151,180,80,29,5,32,212,62,...,2.95,7.76,3.81,1.52,0,0,0,0,1,2022
11,1,1,3,4,5,1,0,0,3,5,...,13.50,10.80,13.50,0.00,0,0,0,0,1,2023

In [24]:
# Column to move to the front
column_to_move = 'season'

# Extract the column
column = ray_df[column_to_move]

# Drop the column from its original position
ray_df.drop(columns=[column_to_move], inplace=True)

# Insert the column at the front
ray_df.insert(0, column_to_move, column)

ray_df.insert(0, 'name', 'Robbie Ray')

ray_pitch = ray_df.loc[:, columns_to_keep]

ray_pitch_comp = ray_pitch[ray_pitch['season'] == '2021']
ray_pitch_comp

,name,season,gamesStarted,wins,losses,inningsPitched,era,earnedRuns,avg,ops,whip,strikeOuts,strikeoutWalkRatio,totalBases,walksPer9Inn,hitsPer9Inn,runsScoredPer9
9,Robbie Ray,2021,32,13,7,193.1,2.84,61,.210,.668,1.04,248,4.77,286,2.42,6.98,2.89

In [25]:
ohtani_pitch_comp = pd.concat([ohtani_pitch_comp, ray_pitch_comp], ignore_index=True)
ohtani_pitch_comp

,name,season,gamesStarted,wins,losses,inningsPitched,era,earnedRuns,avg,ops,whip,strikeOuts,strikeoutWalkRatio,totalBases,walksPer9Inn,hitsPer9Inn,runsScoredPer9
0,Shohei Ohtani,2022,28,15,9,166.0,2.33,43,.203,.574,1.01,219,4.98,193,2.39,6.72,2.44
1,Gerrit Cole,2023,33,15,4,209.0,2.63,61,.206,.581,0.98,222,4.63,245,2.07,6.76,2.76
2,Justin Verlander,2022,28,18,4,175.0,1.75,34,.186,.497,0.83,185,6.38,169,1.49,5.97,2.21
3,Robbie Ray,2021,32,13,7,193.1,2.84,61,.210,.668,1.04,248,4.77,286,2.42,6.98,2.89

In [27]:
ohtani_pitch_comp.transpose()

                                0            1                 2           3
name                Shohei Ohtani  Gerrit Cole  Justin Verlander  Robbie Ray
season                       2022         2023              2022        2021
gamesStarted                   28           33                28          32
wins                           15           15                18          13
losses                          9            4                 4           7
inningsPitched              166.0        209.0             175.0       193.1
era                          2.33         2.63              1.75        2.84
earnedRuns                     43           61                34          61
avg                          .203         .206              .186        .210
ops                          .574         .581              .497        .668
whip                         1.01         0.98              0.83        1.04
strikeOuts                    219          222               185         248
strikeoutWalkRatio           4.98         4.63              6.38        4.77
totalBases                    193          245               169         286
walksPer9Inn                 2.39         2.07              1.49        2.42
hitsPer9Inn                  6.72         6.76              5.97        6.98
runsScoredPer9               2.44         2.76              2.21        2.89

In [28]:
# Given dictionary
data = statsapi.player_stat_data(statsapi.lookup_player('harper, bryce')[0]['id'], group="hitting", type="yearByYear", sportId=1)

# Flatten the dictionary and extract stats for each season
player_stats = []
for season_stats in data['stats']:
    season_data = season_stats['stats']
    season_data['season'] = season_stats['season']
    player_stats.append(season_data)

# Create DataFrame from the list of dictionaries
harper_df = pd.DataFrame(player_stats)

# Display DataFrame
harper_df

,gamesPlayed,groundOuts,airOuts,runs,doubles,triples,homeRuns,strikeOuts,baseOnBalls,intentionalWalks,...,totalBases,rbi,leftOnBase,sacBunts,sacFlies,babip,groundOutsToAirouts,catchersInterference,atBatsPerHomeRun,season
0,139,143,132,98,26,9,22,120,56,0,...,254,59,205,3,3,.310,1.08,0,24.23,2012
1,118,124,97,71,24,3,20,94,61,4,...,206,58,167,3,4,.306,1.28,0,21.20,2013
2,100,79,77,41,10,2,13,104,38,4,...,149,32,148,3,1,.352,1.03,0,27.08,2014
3,153,113,109,118,38,1,42,131,124,15,...,338,99,197,0,4,.369,1.04,0,12.40,2015
4,147,127,149,84,24,2,24,117,108,20,...,223,86,213,0,10,.264,0.85,0,21.08,2016
5,111,85,105,95,27,1,29,99,68,11,...,250,87,174,0,3,.356,0.81,0,14.48,2017
6,159,124,129,103,34,0,34,169,130,16,...,273,100,211,0,9,.289,0.96,0,16.18,2018
7,157,116,134,98,36,1,35,178,99,11,...,292,114,218,0,4,.313,0.87,0,16.37,2019
8,58,44,55,41,9,2,13,43,49,8,...,103,33,88,1,2,.279,0.80,0,14.62,2020
9,141,112,97,101,42,1,35,134,100,14,...,300,84,158,2,4,.359,1.15,0,13.94,2021
10,99,98,86,63,28,1,18,87,46,9,...,190,65,143,0,7,.324,1.14,0,20.56,2022
11,126,115,93,84,29,1,21,119,80,8,...,228,72,171,0,4,.352,1.24,0,21.76,2023

In [29]:
# Column to move to the front
column_to_move = 'season'

# Extract the column
column = harper_df[column_to_move]

# Drop the column from its original position
harper_df.drop(columns=[column_to_move], inplace=True)

# Insert the column at the front
harper_df.insert(0, column_to_move, column)

harper_df.insert(0, 'name', 'Bryce Harper')

# Display the DataFrame
harper_df

,name,season,gamesPlayed,groundOuts,airOuts,runs,doubles,triples,homeRuns,strikeOuts,...,plateAppearances,totalBases,rbi,leftOnBase,sacBunts,sacFlies,babip,groundOutsToAirouts,catchersInterference,atBatsPerHomeRun
0,Bryce Harper,2012,139,143,132,98,26,9,22,120,...,597,254,59,205,3,3,.310,1.08,0,24.23
1,Bryce Harper,2013,118,124,97,71,24,3,20,94,...,497,206,58,167,3,4,.306,1.28,0,21.20
2,Bryce Harper,2014,100,79,77,41,10,2,13,104,...,395,149,32,148,3,1,.352,1.03,0,27.08
3,Bryce Harper,2015,153,113,109,118,38,1,42,131,...,654,338,99,197,0,4,.369,1.04,0,12.40
4,Bryce Harper,2016,147,127,149,84,24,2,24,117,...,627,223,86,213,0,10,.264,0.85,0,21.08
5,Bryce Harper,2017,111,85,105,95,27,1,29,99,...,492,250,87,174,0,3,.356,0.81,0,14.48
6,Bryce Harper,2018,159,124,129,103,34,0,34,169,...,695,273,100,211,0,9,.289,0.96,0,16.18
7,Bryce Harper,2019,157,116,134,98,36,1,35,178,...,682,292,114,218,0,4,.313,0.87,0,16.37
8,Bryce Harper,2020,58,44,55,41,9,2,13,43,...,244,103,33,88,1,2,.279,0.80,0,14.62
9,Bryce Harper,2021,141,112,97,101,42,1,35,134,...,599,300,84,158,2,4,.359,1.15,0,13.94
10,Bryce Harper,2022,99,98,86,63,28,1,18,87,...,426,190,65,143,0,7,.324,1.14,0,20.56
11,Bryce Harper,2023,126,115,93,84,29,1,21,119,...,546,228,72,171,0,4,.352,1.24,0,21.76

In [30]:
harper_df = harper_df[['name', 'season', 'gamesPlayed', 'avg', 'ops', 'homeRuns', 'runs', 'totalBases', 'rbi', 'babip']]
harper_df_comp = harper_df[harper_df['season'] == '2023']
harper_df_comp

,name,season,gamesPlayed,avg,ops,homeRuns,runs,totalBases,rbi,babip
11,Bryce Harper,2023,126,.293,.900,21,84,228,72,.352