In [130]:
import statsapi
import pandas as pd
from pandas import Series, DataFrame

In [131]:
# Given dictionary
data = statsapi.player_stat_data(statsapi.lookup_player('ohtani, shohei')[0]['id'], group="hitting", type="yearByYear", sportId=1)

# Flatten the dictionary and extract stats for each season
player_stats = []
for season_stats in data['stats']:
    season_data = season_stats['stats']
    season_data['season'] = season_stats['season']
    player_stats.append(season_data)

# Create DataFrame from the list of dictionaries
ohtani_df = pd.DataFrame(player_stats)

# Display DataFrame
ohtani_df

,gamesPlayed,groundOuts,airOuts,runs,doubles,triples,homeRuns,strikeOuts,baseOnBalls,intentionalWalks,...,totalBases,rbi,leftOnBase,sacBunts,sacFlies,babip,groundOutsToAirouts,catchersInterference,atBatsPerHomeRun,season
0,114,71,61,59,21,2,22,102,37,2,...,184,61,128,0,1,.350,1.16,1,14.82,2018
1,106,101,67,51,20,5,18,110,33,1,...,194,62,192,0,4,.354,1.51,2,21.33,2019
2,46,44,30,23,6,0,7,50,22,0,...,56,24,99,0,0,.229,1.47,0,21.86,2020
3,158,101,111,103,26,8,46,189,96,20,...,318,100,187,0,2,.303,0.91,0,11.67,2021
4,157,136,132,90,30,6,34,161,72,14,...,304,95,196,0,3,.320,1.03,0,17.24,2022
5,135,103,103,102,26,8,44,143,91,21,...,325,95,194,0,3,.342,1.00,5,11.30,2023

In [132]:
ohtani_df.columns

Index(['gamesPlayed', 'groundOuts', 'airOuts', 'runs', 'doubles', 'triples',
       'homeRuns', 'strikeOuts', 'baseOnBalls', 'intentionalWalks', 'hits',
       'hitByPitch', 'avg', 'atBats', 'obp', 'slg', 'ops', 'caughtStealing',
       'stolenBases', 'stolenBasePercentage', 'groundIntoDoublePlay',
       'numberOfPitches', 'plateAppearances', 'totalBases', 'rbi',
       'leftOnBase', 'sacBunts', 'sacFlies', 'babip', 'groundOutsToAirouts',
       'catchersInterference', 'atBatsPerHomeRun', 'season'],
      dtype='object')

In [133]:
# Column to move to the front
column_to_move = 'season'

# Extract the column
column = ohtani_df[column_to_move]

# Drop the column from its original position
ohtani_df.drop(columns=[column_to_move], inplace=True)

# Insert the column at the front
ohtani_df.insert(0, column_to_move, column)

ohtani_df.insert(0, 'name', 'Shohei Ohtani')

# Display the DataFrame
ohtani_df

,name,season,gamesPlayed,groundOuts,airOuts,runs,doubles,triples,homeRuns,strikeOuts,...,plateAppearances,totalBases,rbi,leftOnBase,sacBunts,sacFlies,babip,groundOutsToAirouts,catchersInterference,atBatsPerHomeRun
0,Shohei Ohtani,2018,114,71,61,59,21,2,22,102,...,367,184,61,128,0,1,.350,1.16,1,14.82
1,Shohei Ohtani,2019,106,101,67,51,20,5,18,110,...,425,194,62,192,0,4,.354,1.51,2,21.33
2,Shohei Ohtani,2020,46,44,30,23,6,0,7,50,...,175,56,24,99,0,0,.229,1.47,0,21.86
3,Shohei Ohtani,2021,158,101,111,103,26,8,46,189,...,639,318,100,187,0,2,.303,0.91,0,11.67
4,Shohei Ohtani,2022,157,136,132,90,30,6,34,161,...,666,304,95,196,0,3,.320,1.03,0,17.24
5,Shohei Ohtani,2023,135,103,103,102,26,8,44,143,...,599,325,95,194,0,3,.342,1.00,5,11.30

In [134]:
ohtani_df = ohtani_df[['name', 'season', 'gamesPlayed', 'avg', 'ops', 'homeRuns', 'runs', 'totalBases', 'rbi', 'babip']]
ohtani_df_comp = ohtani_df[ohtani_df['season'] == '2023']
ohtani_df_comp

,name,season,gamesPlayed,avg,ops,homeRuns,runs,totalBases,rbi,babip
5,Shohei Ohtani,2023,135,.304,1.066,44,102,325,95,.342

In [179]:
ohtani_2019 = ohtani_df[ohtani_df['season'] == '2019']
ohtani_2019

,name,season,gamesPlayed,avg,ops,homeRuns,runs,totalBases,rbi,babip
1,Shohei Ohtani,2019,106,.286,.848,18,51,194,62,.354

In [135]:
# Given dictionary
data = statsapi.player_stat_data(statsapi.lookup_player('judge, aaron')[0]['id'], group="hitting", type="yearByYear", sportId=1)

# Flatten the dictionary and extract stats for each season
player_stats = []
for season_stats in data['stats']:
    season_data = season_stats['stats']
    season_data['season'] = season_stats['season']
    player_stats.append(season_data)

# Create DataFrame from the list of dictionaries
judge_df = pd.DataFrame(player_stats)

# Display DataFrame
judge_df

,gamesPlayed,groundOuts,airOuts,runs,doubles,triples,homeRuns,strikeOuts,baseOnBalls,intentionalWalks,...,totalBases,rbi,leftOnBase,sacBunts,sacFlies,babip,groundOutsToAirouts,catchersInterference,atBatsPerHomeRun,season
0,27,11,17,10,2,0,4,42,9,0,...,29,10,41,0,1,.282,0.65,0,21.00,2016
1,155,85,99,128,24,3,52,208,127,11,...,340,114,248,0,4,.357,0.86,0,10.42,2017
2,112,77,74,77,22,0,27,152,76,3,...,218,67,143,0,5,.368,1.04,0,15.30,2018
3,102,71,64,75,18,1,27,141,64,4,...,204,55,149,0,1,.360,1.11,1,14.00,2019
4,28,22,21,23,3,0,9,32,10,0,...,56,22,49,0,0,.283,1.05,1,11.22,2020
5,148,127,112,89,24,0,39,158,75,2,...,299,98,217,0,5,.332,1.13,0,14.10,2021
6,157,111,112,133,28,0,62,175,111,19,...,391,131,210,0,5,.340,0.99,4,9.19,2022
7,106,54,88,79,16,0,37,130,88,9,...,225,75,127,0,3,.300,0.61,0,9.92,2023

In [136]:
# Column to move to the front
column_to_move = 'season'

# Extract the column
column = judge_df[column_to_move]

# Drop the column from its original position
judge_df.drop(columns=[column_to_move], inplace=True)

# Insert the column at the front
judge_df.insert(0, column_to_move, column)

judge_df.insert(0, 'name', 'Aaron Judge')

# Display the DataFrame
judge_df

,name,season,gamesPlayed,groundOuts,airOuts,runs,doubles,triples,homeRuns,strikeOuts,...,plateAppearances,totalBases,rbi,leftOnBase,sacBunts,sacFlies,babip,groundOutsToAirouts,catchersInterference,atBatsPerHomeRun
0,Aaron Judge,2016,27,11,17,10,2,0,4,42,...,95,29,10,41,0,1,.282,0.65,0,21.00
1,Aaron Judge,2017,155,85,99,128,24,3,52,208,...,678,340,114,248,0,4,.357,0.86,0,10.42
2,Aaron Judge,2018,112,77,74,77,22,0,27,152,...,498,218,67,143,0,5,.368,1.04,0,15.30
3,Aaron Judge,2019,102,71,64,75,18,1,27,141,...,447,204,55,149,0,1,.360,1.11,1,14.00
4,Aaron Judge,2020,28,22,21,23,3,0,9,32,...,114,56,22,49,0,0,.283,1.05,1,11.22
5,Aaron Judge,2021,148,127,112,89,24,0,39,158,...,633,299,98,217,0,5,.332,1.13,0,14.10
6,Aaron Judge,2022,157,111,112,133,28,0,62,175,...,696,391,131,210,0,5,.340,0.99,4,9.19
7,Aaron Judge,2023,106,54,88,79,16,0,37,130,...,458,225,75,127,0,3,.300,0.61,0,9.92

In [137]:
judge_df = judge_df[['name', 'season', 'gamesPlayed', 'avg', 'ops', 'homeRuns', 'runs', 'totalBases', 'rbi', 'babip']]
judge_df_comp = judge_df[judge_df['season'] == '2022']
judge_df_comp

,name,season,gamesPlayed,avg,ops,homeRuns,runs,totalBases,rbi,babip
6,Aaron Judge,2022,157,.311,1.111,62,133,391,131,.340

In [138]:
ohtani_df_comp = ohtani_df_comp.append(judge_df[judge_df['season'] == '2022'])
ohtani_df_comp

C:\Users\jgold\AppData\Local\Temp\ipykernel_8552\2690580331.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  ohtani_df_comp = ohtani_df_comp.append(judge_df[judge_df['season'] == '2022'])

,name,season,gamesPlayed,avg,ops,homeRuns,runs,totalBases,rbi,babip
5,Shohei Ohtani,2023,135,.304,1.066,44,102,325,95,.342
6,Aaron Judge,2022,157,.311,1.111,62,133,391,131,.340

In [139]:
# Given dictionary
data = statsapi.player_stat_data(statsapi.lookup_player('trout, mike')[0]['id'], group="hitting", type="yearByYear", sportId=1)

# Flatten the dictionary and extract stats for each season
player_stats = []
for season_stats in data['stats']:
    season_data = season_stats['stats']
    season_data['season'] = season_stats['season']
    player_stats.append(season_data)

# Create DataFrame from the list of dictionaries
trout_df = pd.DataFrame(player_stats)

# Display DataFrame
trout_df

,gamesPlayed,groundOuts,airOuts,runs,doubles,triples,homeRuns,strikeOuts,baseOnBalls,intentionalWalks,...,totalBases,rbi,leftOnBase,sacBunts,sacFlies,babip,groundOutsToAirouts,catchersInterference,atBatsPerHomeRun,season
0,40,27,40,20,6,0,5,30,9,0,...,48,16,50,0,1,.247,0.68,0,24.60,2011
1,139,133,112,129,27,8,30,139,67,4,...,315,83,169,0,7,.383,1.19,0,18.63,2012
2,157,123,148,109,39,9,27,136,110,10,...,328,97,212,0,8,.376,0.83,0,21.82,2013
3,157,94,161,115,39,9,36,184,83,6,...,338,111,211,0,10,.349,0.58,0,16.72,2014
4,159,112,138,104,32,6,41,158,92,14,...,339,90,166,0,5,.344,0.81,0,14.02,2015
5,159,121,123,123,32,5,29,137,116,12,...,302,100,208,0,5,.371,0.98,0,18.93,2016
6,114,81,112,92,25,3,33,90,94,15,...,253,72,133,0,4,.318,0.72,0,12.18,2017
7,140,75,129,101,24,4,39,124,122,25,...,296,79,139,0,4,.346,0.58,1,12.08,2018
8,134,70,147,110,27,2,45,120,110,14,...,303,104,185,0,4,.298,0.48,0,10.44,2019
9,53,28,63,41,9,2,17,56,35,4,...,120,46,86,0,4,.300,0.44,0,11.71,2020
10,36,20,17,23,8,1,8,41,27,5,...,73,18,40,0,0,.456,1.18,0,14.62,2021
11,119,53,123,85,28,2,40,139,54,8,...,276,80,148,0,1,.323,0.43,0,10.95,2022
12,82,48,77,54,14,1,18,104,45,2,...,151,44,132,0,2,.335,0.62,0,17.11,2023

In [140]:
# Column to move to the front
column_to_move = 'season'

# Extract the column
column = trout_df[column_to_move]

# Drop the column from its original position
trout_df.drop(columns=[column_to_move], inplace=True)

# Insert the column at the front
trout_df.insert(0, column_to_move, column)

trout_df.insert(0, 'name', 'Mike Trout')

# Display the DataFrame
trout_df

,name,season,gamesPlayed,groundOuts,airOuts,runs,doubles,triples,homeRuns,strikeOuts,...,plateAppearances,totalBases,rbi,leftOnBase,sacBunts,sacFlies,babip,groundOutsToAirouts,catchersInterference,atBatsPerHomeRun
0,Mike Trout,2011,40,27,40,20,6,0,5,30,...,135,48,16,50,0,1,.247,0.68,0,24.60
1,Mike Trout,2012,139,133,112,129,27,8,30,139,...,639,315,83,169,0,7,.383,1.19,0,18.63
2,Mike Trout,2013,157,123,148,109,39,9,27,136,...,716,328,97,212,0,8,.376,0.83,0,21.82
3,Mike Trout,2014,157,94,161,115,39,9,36,184,...,705,338,111,211,0,10,.349,0.58,0,16.72
4,Mike Trout,2015,159,112,138,104,32,6,41,158,...,682,339,90,166,0,5,.344,0.81,0,14.02
5,Mike Trout,2016,159,121,123,123,32,5,29,137,...,681,302,100,208,0,5,.371,0.98,0,18.93
6,Mike Trout,2017,114,81,112,92,25,3,33,90,...,507,253,72,133,0,4,.318,0.72,0,12.18
7,Mike Trout,2018,140,75,129,101,24,4,39,124,...,608,296,79,139,0,4,.346,0.58,1,12.08
8,Mike Trout,2019,134,70,147,110,27,2,45,120,...,600,303,104,185,0,4,.298,0.48,0,10.44
9,Mike Trout,2020,53,28,63,41,9,2,17,56,...,241,120,46,86,0,4,.300,0.44,0,11.71
10,Mike Trout,2021,36,20,17,23,8,1,8,41,...,146,73,18,40,0,0,.456,1.18,0,14.62
11,Mike Trout,2022,119,53,123,85,28,2,40,139,...,499,276,80,148,0,1,.323,0.43,0,10.95
12,Mike Trout,2023,82,48,77,54,14,1,18,104,...,362,151,44,132,0,2,.335,0.62,0,17.11

In [141]:
trout_df = trout_df[['name', 'season', 'gamesPlayed', 'avg', 'ops', 'homeRuns', 'runs', 'totalBases', 'rbi', 'babip']]
trout_df_comp = trout_df[trout_df['season'] == '2019']
trout_df_comp

,name,season,gamesPlayed,avg,ops,homeRuns,runs,totalBases,rbi,babip
8,Mike Trout,2019,134,.291,1.083,45,110,303,104,.298

In [142]:
ohtani_df_comp = pd.concat([ohtani_df_comp, trout_df_comp], ignore_index=True)
ohtani_df_comp

,name,season,gamesPlayed,avg,ops,homeRuns,runs,totalBases,rbi,babip
0,Shohei Ohtani,2023,135,.304,1.066,44,102,325,95,.342
1,Aaron Judge,2022,157,.311,1.111,62,133,391,131,.340
2,Mike Trout,2019,134,.291,1.083,45,110,303,104,.298

In [143]:
# Given dictionary
data = statsapi.player_stat_data(statsapi.lookup_player('betts, mookie')[0]['id'], group="hitting", type="yearByYear", sportId=1)

# Flatten the dictionary and extract stats for each season
player_stats = []
for season_stats in data['stats']:
    season_data = season_stats['stats']
    season_data['season'] = season_stats['season']
    player_stats.append(season_data)

# Create DataFrame from the list of dictionaries
betts_df = pd.DataFrame(player_stats)

# Display DataFrame
betts_df

,gamesPlayed,groundOuts,airOuts,runs,doubles,triples,homeRuns,strikeOuts,baseOnBalls,intentionalWalks,...,totalBases,rbi,leftOnBase,sacBunts,sacFlies,babip,groundOutsToAirouts,catchersInterference,atBatsPerHomeRun,season
0,52,44,60,34,12,1,5,31,21,0,...,84,18,68,1,0,.327,0.73,0,37.80,2014
1,145,138,212,92,42,8,18,82,46,1,...,286,77,177,3,6,.310,0.65,0,33.17,2015
2,158,169,216,122,42,5,31,80,49,1,...,359,113,236,0,7,.322,0.78,0,21.68,2016
3,153,165,223,101,46,2,24,79,77,9,...,288,102,230,0,5,.268,0.74,0,26.17,2017
4,136,93,161,129,47,5,32,91,81,8,...,333,80,142,0,5,.368,0.58,0,16.25,2018
5,150,121,208,135,40,5,29,101,97,6,...,313,80,184,0,9,.309,0.58,0,20.59,2019
6,55,38,80,47,9,1,16,38,24,1,...,123,39,65,0,1,.289,0.48,0,13.69,2020
7,122,105,157,93,29,3,23,86,68,2,...,227,58,152,0,5,.276,0.67,0,20.26,2021
8,142,127,191,117,40,3,35,104,55,0,...,305,82,198,0,4,.272,0.66,0,16.34,2022
9,152,97,206,126,40,1,39,107,96,3,...,338,107,167,0,5,.316,0.47,0,14.97,2023

In [144]:
# Column to move to the front
column_to_move = 'season'

# Extract the column
column = betts_df[column_to_move]

# Drop the column from its original position
betts_df.drop(columns=[column_to_move], inplace=True)

# Insert the column at the front
betts_df.insert(0, column_to_move, column)

betts_df.insert(0, 'name', 'Mookie Betts')

# Display the DataFrame
betts_df

,name,season,gamesPlayed,groundOuts,airOuts,runs,doubles,triples,homeRuns,strikeOuts,...,plateAppearances,totalBases,rbi,leftOnBase,sacBunts,sacFlies,babip,groundOutsToAirouts,catchersInterference,atBatsPerHomeRun
0,Mookie Betts,2014,52,44,60,34,12,1,5,31,...,213,84,18,68,1,0,.327,0.73,0,37.80
1,Mookie Betts,2015,145,138,212,92,42,8,18,82,...,654,286,77,177,3,6,.310,0.65,0,33.17
2,Mookie Betts,2016,158,169,216,122,42,5,31,80,...,730,359,113,236,0,7,.322,0.78,0,21.68
3,Mookie Betts,2017,153,165,223,101,46,2,24,79,...,712,288,102,230,0,5,.268,0.74,0,26.17
4,Mookie Betts,2018,136,93,161,129,47,5,32,91,...,614,333,80,142,0,5,.368,0.58,0,16.25
5,Mookie Betts,2019,150,121,208,135,40,5,29,101,...,706,313,80,184,0,9,.309,0.58,0,20.59
6,Mookie Betts,2020,55,38,80,47,9,1,16,38,...,246,123,39,65,0,1,.289,0.48,0,13.69
7,Mookie Betts,2021,122,105,157,93,29,3,23,86,...,550,227,58,152,0,5,.276,0.67,0,20.26
8,Mookie Betts,2022,142,127,191,117,40,3,35,104,...,639,305,82,198,0,4,.272,0.66,0,16.34
9,Mookie Betts,2023,152,97,206,126,40,1,39,107,...,693,338,107,167,0,5,.316,0.47,0,14.97

In [145]:
betts_df = betts_df[['name', 'season', 'gamesPlayed', 'avg', 'ops', 'homeRuns', 'runs', 'totalBases', 'rbi', 'babip']]
betts_df_comp = betts_df[betts_df['season'] == '2018']
betts_df_comp

,name,season,gamesPlayed,avg,ops,homeRuns,runs,totalBases,rbi,babip
4,Mookie Betts,2018,136,.346,1.078,32,129,333,80,.368

In [146]:
ohtani_df_comp = pd.concat([ohtani_df_comp, betts_df_comp], ignore_index=True)
ohtani_df_comp

,name,season,gamesPlayed,avg,ops,homeRuns,runs,totalBases,rbi,babip
0,Shohei Ohtani,2023,135,.304,1.066,44,102,325,95,.342
1,Aaron Judge,2022,157,.311,1.111,62,133,391,131,.340
2,Mike Trout,2019,134,.291,1.083,45,110,303,104,.298
3,Mookie Betts,2018,136,.346,1.078,32,129,333,80,.368

In [147]:
# Given dictionary
data = statsapi.player_stat_data(statsapi.lookup_player('AcuÃ±a Jr., Ronald')[0]['id'], group="hitting", type="yearByYear", sportId=1)

# Flatten the dictionary and extract stats for each season
player_stats = []
for season_stats in data['stats']:
    season_data = season_stats['stats']
    season_data['season'] = season_stats['season']
    player_stats.append(season_data)

# Create DataFrame from the list of dictionaries
acuna_df = pd.DataFrame(player_stats)

# Display DataFrame
acuna_df

,gamesPlayed,groundOuts,airOuts,runs,doubles,triples,homeRuns,strikeOuts,baseOnBalls,intentionalWalks,...,totalBases,rbi,leftOnBase,sacBunts,sacFlies,babip,groundOutsToAirouts,catchersInterference,atBatsPerHomeRun,season
0,111,90,96,78,26,4,26,123,45,2,...,239,64,129,0,3,.352,0.94,0,16.65,2018
1,156,120,144,127,22,2,41,188,76,4,...,324,101,196,0,1,.337,0.83,3,15.27,2019
2,46,29,31,46,11,0,14,60,38,2,...,93,29,56,0,0,.302,0.94,0,11.43,2020
3,82,51,82,72,19,1,24,85,49,2,...,177,52,100,0,5,.311,0.62,0,12.38,2021
4,119,120,100,71,24,0,15,126,53,4,...,193,50,147,0,3,.331,1.20,0,31.13,2022
5,159,193,152,149,35,4,41,84,80,3,...,383,106,186,0,3,.338,1.27,0,15.68,2023

In [148]:
# Column to move to the front
column_to_move = 'season'

# Extract the column
column = acuna_df[column_to_move]

# Drop the column from its original position
acuna_df.drop(columns=[column_to_move], inplace=True)

# Insert the column at the front
acuna_df.insert(0, column_to_move, column)

acuna_df.insert(0, 'name', 'Ronald Acuna Jr.')

# Display the DataFrame
acuna_df

,name,season,gamesPlayed,groundOuts,airOuts,runs,doubles,triples,homeRuns,strikeOuts,...,plateAppearances,totalBases,rbi,leftOnBase,sacBunts,sacFlies,babip,groundOutsToAirouts,catchersInterference,atBatsPerHomeRun
0,Ronald Acuna Jr.,2018,111,90,96,78,26,4,26,123,...,487,239,64,129,0,3,.352,0.94,0,16.65
1,Ronald Acuna Jr.,2019,156,120,144,127,22,2,41,188,...,715,324,101,196,0,1,.337,0.83,3,15.27
2,Ronald Acuna Jr.,2020,46,29,31,46,11,0,14,60,...,202,93,29,56,0,0,.302,0.94,0,11.43
3,Ronald Acuna Jr.,2021,82,51,82,72,19,1,24,85,...,360,177,52,100,0,5,.311,0.62,0,12.38
4,Ronald Acuna Jr.,2022,119,120,100,71,24,0,15,126,...,533,193,50,147,0,3,.331,1.20,0,31.13
5,Ronald Acuna Jr.,2023,159,193,152,149,35,4,41,84,...,735,383,106,186,0,3,.338,1.27,0,15.68

In [149]:
acuna_df = acuna_df[['name', 'season', 'gamesPlayed', 'avg', 'ops', 'homeRuns', 'runs', 'totalBases', 'rbi', 'babip']]
acuna_df_comp = acuna_df[acuna_df['season'] == '2023']
acuna_df_comp

,name,season,gamesPlayed,avg,ops,homeRuns,runs,totalBases,rbi,babip
5,Ronald Acuna Jr.,2023,159,.337,1.012,41,149,383,106,.338

In [150]:
ohtani_df_comp = pd.concat([ohtani_df_comp, acuna_df_comp], ignore_index=True)
ohtani_df_comp

,name,season,gamesPlayed,avg,ops,homeRuns,runs,totalBases,rbi,babip
0,Shohei Ohtani,2023,135,.304,1.066,44,102,325,95,.342
1,Aaron Judge,2022,157,.311,1.111,62,133,391,131,.340
2,Mike Trout,2019,134,.291,1.083,45,110,303,104,.298
3,Mookie Betts,2018,136,.346,1.078,32,129,333,80,.368
4,Ronald Acuna Jr.,2023,159,.337,1.012,41,149,383,106,.338

In [151]:
# Row index to move to the top
row_index_to_move = 4

# Extract the row to move
row_to_move = ohtani_df_comp.iloc[row_index_to_move]

# Drop the row from its original position
ohtani_df_comp = ohtani_df_comp.drop(row_index_to_move)

# Reinsert the row at the beginning of the DataFrame
ohtani_df_comp = pd.concat([row_to_move.to_frame().T, ohtani_df_comp], ignore_index=True)
ohtani_df_comp

,name,season,gamesPlayed,avg,ops,homeRuns,runs,totalBases,rbi,babip
0,Ronald Acuna Jr.,2023,159,.337,1.012,41,149,383,106,.338
1,Shohei Ohtani,2023,135,.304,1.066,44,102,325,95,.342
2,Aaron Judge,2022,157,.311,1.111,62,133,391,131,.340
3,Mike Trout,2019,134,.291,1.083,45,110,303,104,.298
4,Mookie Betts,2018,136,.346,1.078,32,129,333,80,.368

In [170]:
row_to_insert = ohtani_df[ohtani_df['season'] == '2021']
print(row_to_insert)

            name season  gamesPlayed   avg   ops  homeRuns  runs  totalBases  \
3  Shohei Ohtani   2021          158  .257  .964        46   103         318

   rbi babip
3  100  .303

In [171]:
# Index at which to insert
index_to_insert = 3
row_to_insert = ohtani_df[ohtani_df['season'] == '2021']

# Split the main DataFrame into two parts
df_part1 = ohtani_df_comp.iloc[:index_to_insert]
df_part2 = ohtani_df_comp.iloc[index_to_insert:]

# Concatenate the parts along with the DataFrame to insert
ohtani_df_comp = pd.concat([df_part1, row_to_insert, df_part2], ignore_index=True)

ohtani_df_comp

,name,season,gamesPlayed,avg,ops,homeRuns,runs,totalBases,rbi,babip
0,Ronald Acuna Jr.,2023,159,.337,1.012,41,149,383,106,.338
1,Shohei Ohtani,2023,135,.304,1.066,44,102,325,95,.342
2,Aaron Judge,2022,157,.311,1.111,62,133,391,131,.340
3,Shohei Ohtani,2021,158,.257,.964,46,103,318,100,.303
4,Mike Trout,2019,134,.291,1.083,45,110,303,104,.298
5,Mookie Betts,2018,136,.346,1.078,32,129,333,80,.368

In [152]:
#Examine Ohtani pitching stats next
# Given dictionary
data = statsapi.player_stat_data(statsapi.lookup_player('ohtani, shohei')[0]['id'], group="pitching", type="yearByYear", sportId=1)

# Flatten the dictionary and extract stats for each season
player_stats = []
for season_stats in data['stats']:
    season_data = season_stats['stats']
    season_data['season'] = season_stats['season']
    player_stats.append(season_data)

# Create DataFrame from the list of dictionaries
ohtani_pitch = pd.DataFrame(player_stats)

# Display DataFrame
ohtani_pitch

,gamesPlayed,gamesStarted,groundOuts,airOuts,runs,doubles,triples,homeRuns,strikeOuts,baseOnBalls,...,walksPer9Inn,hitsPer9Inn,runsScoredPer9,homeRunsPer9,inheritedRunners,inheritedRunnersScored,catchersInterference,sacBunts,sacFlies,season
0,10,10,37,50,19,6,0,6,63,22,...,3.83,6.62,3.31,1.05,0,0,0,0,1,2018
1,2,2,0,2,7,0,0,0,3,8,...,43.20,16.20,37.80,0.00,0,0,0,0,0,2020
2,23,23,113,112,48,23,0,15,156,44,...,3.04,6.77,3.31,1.04,0,0,0,2,4,2021
3,28,28,129,141,45,23,2,14,219,44,...,2.39,6.72,2.44,0.76,0,0,1,0,3,2022
4,23,23,114,98,50,15,0,18,167,55,...,3.75,5.80,3.41,1.23,0,0,1,0,1,2023

In [153]:
columns_to_keep = ['season', 'gamesStarted', 'wins', 'losses', 'inningsPitched', 'era', 'earnedRuns', 'avg', 'ops', 'whip', 'strikeOuts', 'strikeoutWalkRatio', 'totalBases', 'walksPer9Inn', 'hitsPer9Inn', 'runsScoredPer9']

In [154]:
ohtani_pitch_comp = ohtani_pitch.loc[:, columns_to_keep]
ohtani_pitch_comp

,season,gamesStarted,wins,losses,inningsPitched,era,earnedRuns,avg,ops,whip,strikeOuts,strikeoutWalkRatio,totalBases,walksPer9Inn,hitsPer9Inn,runsScoredPer9
0,2018,10,4,2,51.2,3.31,19,.203,.621,1.16,63,2.86,62,3.83,6.62,3.31
1,2020,2,0,1,1.2,37.80,7,.375,1.063,6.60,3,0.38,3,43.20,16.20,37.80
2,2021,23,9,2,130.1,3.18,46,.207,.637,1.09,156,3.55,166,3.04,6.77,3.31
3,2022,28,15,9,166.0,2.33,43,.203,.574,1.01,219,4.98,193,2.39,6.72,2.44
4,2023,23,10,5,132.0,3.14,46,.184,.618,1.06,167,3.04,154,3.75,5.80,3.41

In [155]:
print(statsapi.league_leaders('earnedRunAverage', season=2023, limit=20, statGroup='pitching', leagueId=None, gameTypes='R', playerPool=None, sportId=1, statType=None))

Rank Name                 Team                    Value
 1   Blake Snell          San Diego Padres        2.25
 2   Gerrit Cole          New York Yankees        2.63
 3   Sonny Gray           Minnesota Twins         2.79
 4   Kyle Bradish         Baltimore Orioles       2.83
 5   Kodai Senga          New York Mets           2.98
 6   Justin Steele        Chicago Cubs            3.06
 7   Kevin Gausman        Toronto Blue Jays       3.16
 8   Jordan Montgomery    Texas Rangers           3.20
 9   Justin Verlander     Houston Astros          3.22
 10  Logan Webb           San Francisco Giants    3.25
 11  Merrill Kelly        Arizona Diamondbacks    3.29
 12  Luis Castillo        Seattle Mariners        3.34
 13  George Kirby         Seattle Mariners        3.35
 14  Corbin Burnes        Milwaukee Brewers       3.39
 15  Framber Valdez       Houston Astros          3.45
 16  Zac Gallen           Arizona Diamondbacks    3.47
 17  Zach Eflin           Tampa Bay Rays          3.50
 18  JesÃºs Luzardo        Miami Marlins           3.58
 19  Chris Bassitt        Toronto Blue Jays       3.60
 20  Zack Wheeler         Philadelphia Phillies   3.61

In [156]:
#Examine Ohtani pitching stats next

pitch_dict = {'Ohtani': statsapi.lookup_player('ohtani, shohei')[0]['id'], 'Cole':statsapi.lookup_player('cole, gerrit')[0]['id']}

data = []
for player_name, player_id in pitch_dict.items():  # Iterate over player names and IDs
    player_data = statsapi.player_stat_data(player_id, group="pitching", type="career", sportId=1)
    player_data['player_name'] = player_name  # Add player name to the data dictionary
    data.append(player_data)

# Flatten the dictionary and extract stats for each season
player_stats = []
for d in data:
    for season_stats in d['stats']:
        season_data = season_stats['stats']
        season_data['season'] = season_stats['season']
        season_data['player_name'] = d['player_name']  # Add player name to each season's data
        player_stats.append(season_data)

# Create DataFrame from the list of dictionaries
ohtani_pitch = pd.DataFrame(player_stats)

# Display DataFrame
ohtani_pitch

,gamesPlayed,gamesStarted,groundOuts,airOuts,runs,doubles,triples,homeRuns,strikeOuts,baseOnBalls,...,hitsPer9Inn,runsScoredPer9,homeRunsPer9,inheritedRunners,inheritedRunnersScored,catchersInterference,sacBunts,sacFlies,season,player_name
0,86,86,393,403,169,67,2,53,608,173,...,6.50,3.16,0.99,0,0,2,2,9,None,Ohtani
1,300,300,1646,1596,702,302,24,206,2152,471,...,7.50,3.40,1.00,0,0,2,36,31,None,Cole

In [157]:
column_name = 'player_name'

# Pop the column from its current position
column = ohtani_pitch.pop(column_name)

# Insert the column at the beginning of the DataFrame
ohtani_pitch.insert(0, column_name, column)

columns_to_keep = ['player_name', 'gamesStarted', 'era', 'avg', 'ops', 'whip', 'strikeoutWalkRatio', 'walksPer9Inn', 'hitsPer9Inn', 'runsScoredPer9']

ohtani_pitch = ohtani_pitch.loc[:, columns_to_keep]
ohtani_pitch

,player_name,gamesStarted,era,avg,ops,whip,strikeoutWalkRatio,walksPer9Inn,hitsPer9Inn,runsScoredPer9
0,Ohtani,86,3.01,.200,.612,1.08,3.51,3.23,6.50,3.16
1,Cole,300,3.17,.225,.645,1.09,4.57,2.28,7.50,3.40

In [158]:
ohtani_pitch

,player_name,gamesStarted,era,avg,ops,whip,strikeoutWalkRatio,walksPer9Inn,hitsPer9Inn,runsScoredPer9
0,Ohtani,86,3.01,.200,.612,1.08,3.51,3.23,6.50,3.16
1,Cole,300,3.17,.225,.645,1.09,4.57,2.28,7.50,3.40

In [159]:
#compare 2023 seasons between Ohtani and Cole

In [160]:
pitch_dict = statsapi.lookup_player('ruth,', season = 1930)
print(pitch_dict)

[{'id': 121578, 'fullName': 'Babe Ruth', 'firstName': 'George', 'lastName': 'Ruth', 'currentTeam': {'id': 147}, 'primaryPosition': {'code': '9', 'abbreviation': 'RF'}, 'useName': 'Babe', 'boxscoreName': 'Ruth', 'nickName': 'The Bambino', 'mlbDebutDate': '1914-07-11', 'nameFirstLast': 'Babe Ruth', 'firstLastName': 'Babe Ruth', 'lastFirstName': 'Ruth, Babe', 'lastInitName': 'Ruth, B', 'initLastName': 'B Ruth', 'fullFMLName': 'George Herman Ruth', 'fullLFMName': 'Ruth, George Herman'}]

In [161]:
statsapi.roster(147, rosterType=None, date='05/01/1930')

'#    C   Arndt Jorgens\n#    OF  Babe Ruth\n#    OF  Ben Chapman\n#    C   Benny Bengough\n#    C   Bill Dickey\n#    P   Bill Henderson\n#    OF  Bill Karlon\n#    SS  Billy Werber\n#    C   Bubbles Hargrave\n#    OF  Cedric Durst\n#    OF  Dusty Cooke\n#    OF  Earle Combs\n#    P   Ed Wells\n#    P   Foster Edwards\n#    P   Frank Barnes\n#    P   George Pipgras\n#    P   Gordon Rhodes\n#    P   Hank Johnson\n#    OF  Harry Rice\n#    P   Herb Pennock\n#    2B  Jimmie Reese\n#    P   Ken Holloway\n#    P   Lefty Gomez\n#    1B  Lou Gehrig\n#    P   Lou McEvoy\n#    SS  Lyn Lary\n#    SS  Mark Koenig\n#    P   Red Ruffing\n#    P   Roy Sherid\n#    P   Sam Gibson\n#    OF  Sammy Byrd\n#    P   Tom Zachary\n#    2B  Tony Lazzeri\n#    P   Waite Hoyt\n#    SS  Yats Wuestling\n'

In [162]:
ruth_data = statsapi.player_stat_data(121578, group='pitching', type="yearByYear", sportId=1)

# Flatten the dictionary and extract stats for each season
ruth_stats = []
for season_data in ruth_data['stats']:
    season_stats = season_data['stats']
    season_stats['season'] = season_data['season']
    ruth_stats.append(season_stats)

# Create DataFrame from the list of dictionaries
ruth_df = pd.DataFrame(ruth_stats)

# Display DataFrame
ruth_df

,gamesPlayed,gamesStarted,runs,homeRuns,strikeOuts,baseOnBalls,hits,hitByPitch,avg,atBats,...,winPercentage,gamesFinished,strikeoutWalkRatio,strikeoutsPer9Inn,walksPer9Inn,hitsPer9Inn,runsScoredPer9,homeRunsPer9,season,sacBunts
0,4,3,12,1,3,7,21,0,.236,89,...,.667,0,0.43,1.17,2.74,8.22,4.70,0.39,1914,NaN
1,32,28,80,3,112,85,166,6,.212,783,...,.692,3,1.32,4.63,3.51,6.86,3.31,0.12,1915,NaN
2,44,41,83,0,170,118,230,8,.201,1146,...,.657,3,1.44,4.73,3.28,6.40,2.31,0.00,1916,NaN
3,41,38,93,2,128,108,244,11,.211,1158,...,.649,3,1.19,3.53,2.98,6.73,2.56,0.06,1917,NaN
4,20,19,51,1,40,49,125,2,.205,609,...,.650,0,0.82,2.16,2.65,6.76,2.76,0.05,1918,NaN
5,17,15,59,2,30,58,148,2,.290,510,...,.643,2,0.52,2.03,3.92,9.99,3.98,0.13,1919,NaN
6,1,1,4,0,0,2,3,0,.200,15,...,1.000,0,0.00,0.00,4.50,6.75,9.00,0.00,1920,NaN
7,2,1,10,1,2,9,14,0,.350,40,...,1.000,1,0.22,2.00,9.00,14.00,10.00,1.00,1921,0.0
8,1,1,3,0,3,2,11,0,.306,36,...,1.000,0,1.50,3.00,2.00,11.00,3.00,0.00,1930,1.0
9,1,1,5,0,0,3,12,0,.308,39,...,1.000,0,0.00,0.00,3.00,12.00,5.00,0.00,1933,0.0

In [163]:
column_name = 'season'

# Pop the column from its current position
column = ruth_df.pop(column_name)

# Insert the column at the beginning of the DataFrame
ruth_df.insert(0, column_name, column)

columns_to_keep = ['gamesStarted', 'season', 'era', 'avg', 'whip', 'strikeoutWalkRatio', 'walksPer9Inn', 'hitsPer9Inn', 'runsScoredPer9']

ruth_pitch = ruth_df.loc[:, columns_to_keep]
ruth_pitch

,gamesStarted,season,era,avg,whip,strikeoutWalkRatio,walksPer9Inn,hitsPer9Inn,runsScoredPer9
0,3,1914,3.91,.236,1.22,0.43,2.74,8.22,4.70
1,28,1915,2.44,.212,1.15,1.32,3.51,6.86,3.31
2,41,1916,1.75,.201,1.08,1.44,3.28,6.40,2.31
3,38,1917,2.01,.211,1.08,1.19,2.98,6.73,2.56
4,19,1918,2.22,.205,1.05,0.82,2.65,6.76,2.76
5,15,1919,2.97,.290,1.55,0.52,3.92,9.99,3.98
6,1,1920,4.50,.200,1.25,0.00,4.50,6.75,9.00
7,1,1921,9.00,.350,2.56,0.22,9.00,14.00,10.00
8,1,1930,3.00,.306,1.44,1.50,2.00,11.00,3.00
9,1,1933,5.00,.308,1.67,0.00,3.00,12.00,5.00

In [164]:
ruth_data

{'id': 121578,
 'first_name': 'Babe',
 'last_name': 'Ruth',
 'active': False,
 'current_team': 'Boston Braves',
 'position': 'RF',
 'nickname': 'The Bambino',
 'last_played': '1935-05-30',
 'mlb_debut': '1914-07-11',
 'bat_side': 'Left',
 'pitch_hand': 'Left',
 'stats': [{'type': 'yearByYear',
   'group': 'pitching',
   'season': '1914',
   'stats': {'gamesPlayed': 4,
    'gamesStarted': 3,
    'runs': 12,
    'homeRuns': 1,
    'strikeOuts': 3,
    'baseOnBalls': 7,
    'hits': 21,
    'hitByPitch': 0,
    'avg': '.236',
    'atBats': 89,
    'obp': '.292',
    'era': '3.91',
    'inningsPitched': '23.0',
    'wins': 2,
    'losses': 1,
    'saves': 0,
    'earnedRuns': 10,
    'whip': '1.22',
    'battersFaced': 96,
    'outs': 69,
    'gamesPitched': 4,
    'completeGames': 1,
    'shutouts': 0,
    'hitBatsmen': 0,
    'balks': 0,
    'wildPitches': 0,
    'winPercentage': '.667',
    'gamesFinished': 0,
    'strikeoutWalkRatio': '0.43',
    'strikeoutsPer9Inn': '1.17',
    'walksPer9Inn': '2.74',
    'hitsPer9Inn': '8.22',
    'runsScoredPer9': '4.70',
    'homeRunsPer9': '0.39',
    'season': '1914'}},
  {'type': 'yearByYear',
   'group': 'pitching',
   'season': '1915',
   'stats': {'gamesPlayed': 32,
    'gamesStarted': 28,
    'runs': 80,
    'homeRuns': 3,
    'strikeOuts': 112,
    'baseOnBalls': 85,
    'hits': 166,
    'hitByPitch': 6,
    'avg': '.212',
    'atBats': 783,
    'obp': '.294',
    'era': '2.44',
    'inningsPitched': '217.2',
    'wins': 18,
    'losses': 8,
    'saves': 0,
    'earnedRuns': 59,
    'whip': '1.15',
    'battersFaced': 874,
    'outs': 653,
    'gamesPitched': 32,
    'completeGames': 16,
    'shutouts': 1,
    'hitBatsmen': 6,
    'balks': 1,
    'wildPitches': 9,
    'winPercentage': '.692',
    'gamesFinished': 3,
    'strikeoutWalkRatio': '1.32',
    'strikeoutsPer9Inn': '4.63',
    'walksPer9Inn': '3.51',
    'hitsPer9Inn': '6.86',
    'runsScoredPer9': '3.31',
    'homeRunsPer9': '0.12',
    'season': '1915'}},
  {'type': 'yearByYear',
   'group': 'pitching',
   'season': '1916',
   'stats': {'gamesPlayed': 44,
    'gamesStarted': 41,
    'runs': 83,
    'homeRuns': 0,
    'strikeOuts': 170,
    'baseOnBalls': 118,
    'hits': 230,
    'hitByPitch': 8,
    'avg': '.201',
    'atBats': 1146,
    'obp': '.280',
    'era': '1.75',
    'inningsPitched': '323.2',
    'wins': 23,
    'losses': 12,
    'saves': 1,
    'earnedRuns': 63,
    'whip': '1.08',
    'battersFaced': 1272,
    'outs': 971,
    'gamesPitched': 44,
    'completeGames': 23,
    'shutouts': 9,
    'hitBatsmen': 8,
    'balks': 1,
    'wildPitches': 3,
    'winPercentage': '.657',
    'gamesFinished': 3,
    'strikeoutWalkRatio': '1.44',
    'strikeoutsPer9Inn': '4.73',
    'walksPer9Inn': '3.28',
    'hitsPer9Inn': '6.40',
    'runsScoredPer9': '2.31',
    'homeRunsPer9': '0.00',
    'season': '1916'}},
  {'type': 'yearByYear',
   'group': 'pitching',
   'season': '1917',
   'stats': {'gamesPlayed': 41,
    'gamesStarted': 38,
    'runs': 93,
    'homeRuns': 2,
    'strikeOuts': 128,
    'baseOnBalls': 108,
    'hits': 244,
    'hitByPitch': 11,
    'avg': '.211',
    'atBats': 1158,
    'obp': '.284',
    'era': '2.01',
    'inningsPitched': '326.1',
    'wins': 24,
    'losses': 13,
    'saves': 2,
    'earnedRuns': 73,
    'whip': '1.08',
    'battersFaced': 1277,
    'outs': 979,
    'gamesPitched': 41,
    'completeGames': 35,
    'shutouts': 6,
    'hitBatsmen': 11,
    'balks': 0,
    'wildPitches': 5,
    'winPercentage': '.649',
    'gamesFinished': 3,
    'strikeoutWalkRatio': '1.19',
    'strikeoutsPer9Inn': '3.53',
    'walksPer9Inn': '2.98',
    'hitsPer9Inn': '6.73',
    'runsScoredPer9': '2.56',
    'homeRunsPer9': '0.06',
    'season': '1917'}},
  {'type': 'yearByYear',
   'group': 'pitching',
   'season': '1918',
   'stats': {'gamesPlayed': 20,
    'gamesStarted': 19,
    'runs': 51,
    'homeRuns': 1,
    'strikeOuts': 40,
    'baseOnBalls': 49,
    'hits': 125,
    'hitByPitch': 2,
    'avg': '.205',
    'atBats': 609,
    'obp': '.267',
    'era': '2.22',
    'inningsPitched': '166.1',
    'wins': 13,
    'losses': 7,
    'saves': 0,
    'earnedRuns': 41,
    'whip': '1.05',
    'battersFaced': 660,
    'outs': 499,
    'gamesPitched': 20,
    'completeGames': 18,
    'shutouts': 1,
    'hitBatsmen': 2,
    'balks': 1,
    'wildPitches': 3,
    'winPercentage': '.650',
    'gamesFinished': 0,
    'strikeoutWalkRatio': '0.82',
    'strikeoutsPer9Inn': '2.16',
    'walksPer9Inn': '2.65',
    'hitsPer9Inn': '6.76',
    'runsScoredPer9': '2.76',
    'homeRunsPer9': '0.05',
    'season': '1918'}},
  {'type': 'yearByYear',
   'group': 'pitching',
   'season': '1919',
   'stats': {'gamesPlayed': 17,
    'gamesStarted': 15,
    'runs': 59,
    'homeRuns': 2,
    'strikeOuts': 30,
    'baseOnBalls': 58,
    'hits': 148,
    'hitByPitch': 2,
    'avg': '.290',
    'atBats': 510,
    'obp': '.365',
    'era': '2.97',
    'inningsPitched': '133.1',
    'wins': 9,
    'losses': 5,
    'saves': 1,
    'earnedRuns': 44,
    'whip': '1.55',
    'battersFaced': 570,
    'outs': 400,
    'gamesPitched': 17,
    'completeGames': 12,
    'shutouts': 0,
    'hitBatsmen': 2,
    'balks': 1,
    'wildPitches': 5,
    'winPercentage': '.643',
    'gamesFinished': 2,
    'strikeoutWalkRatio': '0.52',
    'strikeoutsPer9Inn': '2.03',
    'walksPer9Inn': '3.92',
    'hitsPer9Inn': '9.99',
    'runsScoredPer9': '3.98',
    'homeRunsPer9': '0.13',
    'season': '1919'}},
  {'type': 'yearByYear',
   'group': 'pitching',
   'season': '1920',
   'stats': {'gamesPlayed': 1,
    'gamesStarted': 1,
    'runs': 4,
    'homeRuns': 0,
    'strikeOuts': 0,
    'baseOnBalls': 2,
    'hits': 3,
    'hitByPitch': 0,
    'avg': '.200',
    'atBats': 15,
    'obp': '.294',
    'era': '4.50',
    'inningsPitched': '4.0',
    'wins': 1,
    'losses': 0,
    'saves': 0,
    'earnedRuns': 2,
    'whip': '1.25',
    'battersFaced': 17,
    'outs': 12,
    'gamesPitched': 1,
    'completeGames': 0,
    'shutouts': 0,
    'hitBatsmen': 0,
    'balks': 0,
    'wildPitches': 0,
    'winPercentage': '1.000',
    'gamesFinished': 0,
    'strikeoutWalkRatio': '0.00',
    'strikeoutsPer9Inn': '0.00',
    'walksPer9Inn': '4.50',
    'hitsPer9Inn': '6.75',
    'runsScoredPer9': '9.00',
    'homeRunsPer9': '0.00',
    'season': '1920'}},
  {'type': 'yearByYear',
   'group': 'pitching',
   'season': '1921',
   'stats': {'gamesPlayed': 2,
    'gamesStarted': 1,
    'runs': 10,
    'homeRuns': 1,
    'strikeOuts': 2,
    'baseOnBalls': 9,
    'hits': 14,
    'hitByPitch': 0,
    'avg': '.350',
    'atBats': 40,
    'obp': '.469',
    'era': '9.00',
    'inningsPitched': '9.0',
    'wins': 2,
    'losses': 0,
    'saves': 0,
    'earnedRuns': 9,
    'whip': '2.56',
    'battersFaced': 49,
    'outs': 27,
    'gamesPitched': 2,
    'completeGames': 0,
    'shutouts': 0,
    'hitBatsmen': 0,
    'balks': 0,
    'wildPitches': 0,
    'winPercentage': '1.000',
    'gamesFinished': 1,
    'strikeoutWalkRatio': '0.22',
    'strikeoutsPer9Inn': '2.00',
    'walksPer9Inn': '9.00',
    'hitsPer9Inn': '14.00',
    'runsScoredPer9': '10.00',
    'homeRunsPer9': '1.00',
    'sacBunts': 0,
    'season': '1921'}},
  {'type': 'yearByYear',
   'group': 'pitching',
   'season': '1930',
   'stats': {'gamesPlayed': 1,
    'gamesStarted': 1,
    'runs': 3,
    'homeRuns': 0,
    'strikeOuts': 3,
    'baseOnBalls': 2,
    'hits': 11,
    'hitByPitch': 0,
    'avg': '.306',
    'atBats': 36,
    'obp': '.342',
    'era': '3.00',
    'inningsPitched': '9.0',
    'wins': 1,
    'losses': 0,
    'saves': 0,
    'earnedRuns': 3,
    'whip': '1.44',
    'battersFaced': 39,
    'outs': 27,
    'gamesPitched': 1,
    'completeGames': 1,
    'shutouts': 0,
    'hitBatsmen': 0,
    'balks': 0,
    'wildPitches': 0,
    'winPercentage': '1.000',
    'gamesFinished': 0,
    'strikeoutWalkRatio': '1.50',
    'strikeoutsPer9Inn': '3.00',
    'walksPer9Inn': '2.00',
    'hitsPer9Inn': '11.00',
    'runsScoredPer9': '3.00',
    'homeRunsPer9': '0.00',
    'sacBunts': 1,
    'season': '1930'}},
  {'type': 'yearByYear',
   'group': 'pitching',
   'season': '1933',
   'stats': {'gamesPlayed': 1,
    'gamesStarted': 1,
    'runs': 5,
    'homeRuns': 0,
    'strikeOuts': 0,
    'baseOnBalls': 3,
    'hits': 12,
    'hitByPitch': 0,
    'avg': '.308',
    'atBats': 39,
    'obp': '.357',
    'era': '5.00',
    'inningsPitched': '9.0',
    'wins': 1,
    'losses': 0,
    'saves': 0,
    'earnedRuns': 5,
    'whip': '1.67',
    'battersFaced': 42,
    'outs': 27,
    'gamesPitched': 1,
    'completeGames': 1,
    'shutouts': 0,
    'hitBatsmen': 0,
    'balks': 0,
    'wildPitches': 0,
    'winPercentage': '1.000',
    'gamesFinished': 0,
    'strikeoutWalkRatio': '0.00',
    'strikeoutsPer9Inn': '0.00',
    'walksPer9Inn': '3.00',
    'hitsPer9Inn': '12.00',
    'runsScoredPer9': '5.00',
    'homeRunsPer9': '0.00',
    'sacBunts': 0,
    'season': '1933'}}]}

In [172]:
# Given dictionary
data = statsapi.player_stat_data(statsapi.lookup_player('freeman, freddie')[0]['id'], group="hitting", type="yearByYear", sportId=1)

# Flatten the dictionary and extract stats for each season
player_stats = []
for season_stats in data['stats']:
    season_data = season_stats['stats']
    season_data['season'] = season_stats['season']
    player_stats.append(season_data)

# Create DataFrame from the list of dictionaries
freeman_df = pd.DataFrame(player_stats)

# Display DataFrame
freeman_df

,gamesPlayed,groundOuts,airOuts,runs,doubles,triples,homeRuns,strikeOuts,baseOnBalls,intentionalWalks,...,totalBases,rbi,leftOnBase,sacBunts,sacFlies,babip,groundOutsToAirouts,catchersInterference,atBatsPerHomeRun,season
0,20,7,5,3,1,0,1,8,0,0,...,8,1,13,0,0,.200,1.40,0,24.00,2010
1,157,142,131,67,32,0,21,142,53,3,...,256,76,229,0,5,.339,1.08,0,27.19,2011
2,147,122,158,91,33,2,23,129,64,4,...,246,94,260,0,9,.295,0.77,0,23.48,2012
3,147,129,130,89,27,2,23,121,66,10,...,276,109,193,0,5,.371,0.99,0,23.96,2013
4,162,140,150,93,43,4,18,145,90,4,...,280,78,233,0,3,.351,0.93,0,33.72,2014
5,118,94,111,62,27,0,18,98,56,4,...,196,66,171,0,2,.321,0.85,0,23.11,2015
6,158,102,143,102,43,6,34,171,89,18,...,335,91,217,0,5,.370,0.71,0,17.32,2016
7,117,93,119,84,35,2,28,95,65,14,...,258,71,157,0,2,.335,0.78,0,15.71,2017
8,162,147,154,94,44,4,23,132,76,12,...,312,98,220,0,6,.358,0.95,0,26.87,2018
9,158,143,153,113,34,2,38,127,87,11,...,328,121,210,0,2,.318,0.93,0,15.71,2019
10,60,45,59,51,23,1,13,37,45,7,...,137,53,80,0,0,.366,0.76,0,16.46,2020
11,159,163,152,120,25,2,31,107,85,15,...,302,83,202,0,2,.321,1.07,0,19.36,2021
12,159,142,176,117,47,2,21,102,84,12,...,313,100,207,0,7,.359,0.81,0,29.14,2022
13,161,148,162,131,59,2,29,121,72,12,...,361,102,237,0,5,.370,0.91,0,21.97,2023

In [173]:
# Column to move to the front
column_to_move = 'season'

# Extract the column
column = freeman_df[column_to_move]

# Drop the column from its original position
freeman_df.drop(columns=[column_to_move], inplace=True)

# Insert the column at the front
freeman_df.insert(0, column_to_move, column)

freeman_df.insert(0, 'name', 'Freddie Freeman')

# Display the DataFrame
freeman_df

,name,season,gamesPlayed,groundOuts,airOuts,runs,doubles,triples,homeRuns,strikeOuts,...,plateAppearances,totalBases,rbi,leftOnBase,sacBunts,sacFlies,babip,groundOutsToAirouts,catchersInterference,atBatsPerHomeRun
0,Freddie Freeman,2010,20,7,5,3,1,0,1,8,...,24,8,1,13,0,0,.200,1.40,0,24.00
1,Freddie Freeman,2011,157,142,131,67,32,0,21,142,...,635,256,76,229,0,5,.339,1.08,0,27.19
2,Freddie Freeman,2012,147,122,158,91,33,2,23,129,...,620,246,94,260,0,9,.295,0.77,0,23.48
3,Freddie Freeman,2013,147,129,130,89,27,2,23,121,...,629,276,109,193,0,5,.371,0.99,0,23.96
4,Freddie Freeman,2014,162,140,150,93,43,4,18,145,...,708,280,78,233,0,3,.351,0.93,0,33.72
5,Freddie Freeman,2015,118,94,111,62,27,0,18,98,...,481,196,66,171,0,2,.321,0.85,0,23.11
6,Freddie Freeman,2016,158,102,143,102,43,6,34,171,...,693,335,91,217,0,5,.370,0.71,0,17.32
7,Freddie Freeman,2017,117,93,119,84,35,2,28,95,...,514,258,71,157,0,2,.335,0.78,0,15.71
8,Freddie Freeman,2018,162,147,154,94,44,4,23,132,...,707,312,98,220,0,6,.358,0.95,0,26.87
9,Freddie Freeman,2019,158,143,153,113,34,2,38,127,...,692,328,121,210,0,2,.318,0.93,0,15.71
10,Freddie Freeman,2020,60,45,59,51,23,1,13,37,...,262,137,53,80,0,0,.366,0.76,0,16.46
11,Freddie Freeman,2021,159,163,152,120,25,2,31,107,...,695,302,83,202,0,2,.321,1.07,0,19.36
12,Freddie Freeman,2022,159,142,176,117,47,2,21,102,...,708,313,100,207,0,7,.359,0.81,0,29.14
13,Freddie Freeman,2023,161,148,162,131,59,2,29,121,...,730,361,102,237,0,5,.370,0.91,0,21.97

In [175]:
freeman_df = freeman_df[['name', 'season', 'gamesPlayed', 'avg', 'ops', 'homeRuns', 'runs', 'totalBases', 'rbi', 'babip']]
freeman_df

,name,season,gamesPlayed,avg,ops,homeRuns,runs,totalBases,rbi,babip
0,Freddie Freeman,2010,20,.167,.500,1,3,8,1,.200
1,Freddie Freeman,2011,157,.282,.794,21,67,256,76,.339
2,Freddie Freeman,2012,147,.259,.796,23,91,246,94,.295
3,Freddie Freeman,2013,147,.319,.897,23,89,276,109,.371
4,Freddie Freeman,2014,162,.288,.847,18,93,280,78,.351
5,Freddie Freeman,2015,118,.276,.841,18,62,196,66,.321
6,Freddie Freeman,2016,158,.302,.969,34,102,335,91,.370
7,Freddie Freeman,2017,117,.307,.989,28,84,258,71,.335
8,Freddie Freeman,2018,162,.309,.893,23,94,312,98,.358
9,Freddie Freeman,2019,158,.295,.938,38,113,328,121,.318
10,Freddie Freeman,2020,60,.341,1.102,13,51,137,53,.366
11,Freddie Freeman,2021,159,.300,.896,31,120,302,83,.321
12,Freddie Freeman,2022,159,.325,.918,21,117,313,100,.359
13,Freddie Freeman,2023,161,.331,.977,29,131,361,102,.370

In [176]:
# Index at which to insert
index_to_insert = 4
row_to_insert = freeman_df[freeman_df['season'] == '2020']

# Split the main DataFrame into two parts
df_part1 = ohtani_df_comp.iloc[:index_to_insert]
df_part2 = ohtani_df_comp.iloc[index_to_insert:]

# Concatenate the parts along with the DataFrame to insert
ohtani_df_comp = pd.concat([df_part1, row_to_insert, df_part2], ignore_index=True)

ohtani_df_comp

,name,season,gamesPlayed,avg,ops,homeRuns,runs,totalBases,rbi,babip,...,stolenBasePercentage,groundIntoDoublePlay,numberOfPitches,plateAppearances,leftOnBase,sacBunts,sacFlies,groundOutsToAirouts,catchersInterference,atBatsPerHomeRun
0,Ronald Acuna Jr.,2023,159,.337,1.012,41,149,383,106,.338,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Shohei Ohtani,2023,135,.304,1.066,44,102,325,95,.342,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Aaron Judge,2022,157,.311,1.111,62,133,391,131,.340,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Shohei Ohtani,2021,158,.257,.964,46,103,318,100,.303,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Freddie Freeman,2020,60,.341,1.102,13,51,137,53,.366,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Freddie Freeman,2020,60,.341,1.102,13,51,137,53,.366,...,1.000,6.0,1021.0,262.0,80.0,0.0,0.0,0.76,0.0,16.46
6,Mike Trout,2019,134,.291,1.083,45,110,303,104,.298,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Mookie Betts,2018,136,.346,1.078,32,129,333,80,.368,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [177]:
# Drop a row by index
index_to_drop = 4  # Index of the row to drop
ohtani_df_comp = ohtani_df_comp.drop(index_to_drop)
ohtani_df_comp

,name,season,gamesPlayed,avg,ops,homeRuns,runs,totalBases,rbi,babip,...,stolenBasePercentage,groundIntoDoublePlay,numberOfPitches,plateAppearances,leftOnBase,sacBunts,sacFlies,groundOutsToAirouts,catchersInterference,atBatsPerHomeRun
0,Ronald Acuna Jr.,2023,159,.337,1.012,41,149,383,106,.338,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Shohei Ohtani,2023,135,.304,1.066,44,102,325,95,.342,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Aaron Judge,2022,157,.311,1.111,62,133,391,131,.340,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Shohei Ohtani,2021,158,.257,.964,46,103,318,100,.303,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Freddie Freeman,2020,60,.341,1.102,13,51,137,53,.366,...,1.000,6.0,1021.0,262.0,80.0,0.0,0.0,0.76,0.0,16.46
6,Mike Trout,2019,134,.291,1.083,45,110,303,104,.298,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Mookie Betts,2018,136,.346,1.078,32,129,333,80,.368,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [178]:
ohtani_df_comp = ohtani_df_comp[['name', 'season', 'gamesPlayed', 'avg', 'ops', 'homeRuns', 'runs', 'totalBases', 'rbi', 'babip']]
ohtani_df_comp

,name,season,gamesPlayed,avg,ops,homeRuns,runs,totalBases,rbi,babip
0,Ronald Acuna Jr.,2023,159,.337,1.012,41,149,383,106,.338
1,Shohei Ohtani,2023,135,.304,1.066,44,102,325,95,.342
2,Aaron Judge,2022,157,.311,1.111,62,133,391,131,.340
3,Shohei Ohtani,2021,158,.257,.964,46,103,318,100,.303
5,Freddie Freeman,2020,60,.341,1.102,13,51,137,53,.366
6,Mike Trout,2019,134,.291,1.083,45,110,303,104,.298
7,Mookie Betts,2018,136,.346,1.078,32,129,333,80,.368